import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Brain, RotateCcw, Share2 } from 'lucide-react';
import { Link } from 'react-router-dom';
import { createPageUrl } from '@/utils';
import StyleCarousel from '../results/StyleCarousel';

export default function EnhancedResults({ 
  recommendations, 
  facialHairRecommendations = [],
  generatedPreviews = [],
  faceShape, 
  ethnicity,
  gender,
  ageGroup,
  hairLength,
  hairType,
  hairThickness,
  onStartOver,
  onSaveStyle,
  onShareStyle
}) {
  const handleSaveStyle = (style, type) => {
    // Save to user's favorites/history
    onSaveStyle?.(style, type);
  };

  const handleShareStyle = (style, preview, type) => {
    if (navigator.share && preview) {
      navigator.share({
        title: `Check out my ${type} style: ${style.style_name}`,
        text: `See how I'll look with the ${style.style_name} from BarberAI`,
        url: preview.image_url
      });
    } else {
      // Fallback: copy link to clipboard
      const shareText = `Check out my ${type} style: ${style.style_name} - Generated by BarberAI`;
      navigator.clipboard.writeText(shareText);
    }
    onShareStyle?.(style, preview, type);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <Card className="luxury-shadow border-0 bg-gradient-to-r from-gray-50 to-white">
        <CardHeader className="text-center">
          <div className="flex justify-center mb-4">
            <img 
              src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/52e9d0af4_Screenshot2025-06-20at113022AM.png" 
              alt="BarberAI Logo"
              className="w-12 h-12 object-contain"
            />
          </div>
          <CardTitle className="text-2xl">Your Personalized Results</CardTitle>
          <p className="text-gray-600">
            Swipe through your custom hairstyle recommendations
          </p>
        </CardHeader>
      </Card>

      {/* Analysis Summary */}
      <Card className="luxury-shadow border-0 bg-gradient-to-r from-green-50 to-blue-50 border-green-200">
        <CardContent className="p-6">
          <div className="flex items-center justify-center space-x-4 mb-4">
            <Brain className="w-8 h-8 text-green-600" />
            <h3 className="text-xl font-semibold text-gray-900">AI Analysis Complete</h3>
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-center">
            <div className="bg-white rounded-lg p-3 border">
              <p className="text-sm text-gray-600 mb-1">Face Shape</p>
              <p className="font-semibold text-gray-900 capitalize">{faceShape}</p>
            </div>
            <div className="bg-white rounded-lg p-3 border">
              <p className="text-sm text-gray-600 mb-1">Hair Length</p>
              <p className="font-semibold text-gray-900">{hairLength}</p>
            </div>
            <div className="bg-white rounded-lg p-3 border">
              <p className="text-sm text-gray-600 mb-1">Hair Type</p>
              <p className="font-semibold text-gray-900">{hairType}</p>
            </div>
            <div className="bg-white rounded-lg p-3 border">
              <p className="text-sm text-gray-600 mb-1">Ethnicity</p>
              <p className="font-semibold text-gray-900 text-xs">{ethnicity}</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Hair Style Recommendations */}
      {recommendations && recommendations.length > 0 && (
        <div className="space-y-4">
          <h3 className="text-2xl font-bold text-center text-gray-900">Hairstyle Recommendations</h3>
          <StyleCarousel
            recommendations={recommendations}
            previews={generatedPreviews}
            type="hair"
            onSave={handleSaveStyle}
            onShare={handleShareStyle}
          />
        </div>
      )}

      {/* Facial Hair Recommendations */}
      {facialHairRecommendations && facialHairRecommendations.length > 0 && (
        <div className="space-y-4">
          <h3 className="text-2xl font-bold text-center text-gray-900">Facial Hair Styles</h3>
          <StyleCarousel
            recommendations={facialHairRecommendations}
            previews={generatedPreviews}
            type="facial_hair"
            onSave={handleSaveStyle}
            onShare={handleShareStyle}
          />
        </div>
      )}

      {/* Action Buttons */}
      <div className="flex flex-col sm:flex-row gap-4 justify-center pt-6">
        <Button variant="outline" onClick={onStartOver} size="lg">
          <RotateCcw className="w-5 h-5 mr-2" />
          Try Another Photo
        </Button>
        
        <Link to={createPageUrl('Dashboard')}>
          <Button className="barber-gradient text-white" size="lg">
            <img 
              src="https://qtrypzzcjebvfcihiynt.supabase.co/storage/v1/object/public/base44-prod/public/52e9d0af4_Screenshot2025-06-20at113022AM.png" 
              alt="BarberAI"
              className="w-5 h-5 mr-2 object-contain"
            />
            View My History
          </Button>
        </Link>
      </div>
    </div>
  );
}
